"""Constantes compartilhadas da aplicacao."""

DEFAULT_PAGE = 1
DEFAULT_PAGE_SIZE = 20
MIN_PAGE_SIZE = 1
MAX_PAGE_SIZE = 100

DEFAULT_QUERY_OFFSET = 0
DEFAULT_QUERY_LIMIT = 100

MAX_USER_NAME_LENGTH = 120
MAX_EMAIL_LENGTH = 255
MAX_PASSWORD_HASH_LENGTH = 255

MAX_TWITTER_USERNAME_LENGTH = 50
MAX_TWITTER_DISPLAY_NAME_LENGTH = 120
MAX_TWITTER_USER_ID_LENGTH = 64

MAX_PLAN_NAME_LENGTH = 80

POST_TEXT_MAX_LENGTH = 280

PLAN_FREE = "free"
PLAN_PRO = "pro"
PLAN_BUSINESS = "business"

ERROR_USER_NOT_FOUND = "Usuario nao encontrado."
ERROR_PLAN_NOT_FOUND = "Plano nao encontrado."
ERROR_POST_NOT_FOUND = "Post nao encontrado."
ERROR_TWITTER_ACCOUNT_NOT_FOUND = "Conta do X nao encontrada."
ERROR_EMAIL_ALREADY_EXISTS = "Email ja cadastrado."
ERROR_FEATURE_NOT_IMPLEMENTED = "Funcionalidade ainda nao implementada."
